### ISSUE TITLE
Startup screen

### ISSUE THREAD

**Issue by elmutt** [keepkey/keepkey-desktop#139]
A.C

detect state of keepkey

if update to date and init, LOAD the dashboard and show balances

if firmware update needed launch modal for firmware

if init needed launch modal for init

if no device connected, launch modal for connect device

if no device (show troubleshoot button) (is device connected? troubleshoot)
                Troubleshoot gives info on OS, Devices connected to Host, gives USB info for linux (usb host drivers) and finally takes to support)

**Comment by battlejoose** [comment]
Looks like the troubleshoot button is the only thing I couldnt find.

Set up a fresh keepkey, was detected that it needed updates and did them automatically.

When using updated keepkey detects and brings user to dashboard.
