### ISSUE TITLE
(Bug) Connection Failed for Uniswap dapp

### ISSUE THREAD

**Issue by illithics** [keepkey/keepkey-desktop#205]
Copy address to keyboard from [uniswap.](https://app.uniswap.org/#/swap)
Fails to load

Recreate:
Connect to dApp
Copy address from https://app.uniswap.org/#/swap
Paste address in KK app
Fails to load

![Image](https://user-images.githubusercontent.com/47842709/198741868-5b7aa152-0bf8-4b55-bdfb-30bcfb3af456.png)

**Comment by BitHighlander** [comment]
I believe this is windows specific error
