### ISSUE TITLE
(Bug) (Win) Uncaught Exception - installing 1.76 build

### ISSUE THREAD

**Issue by illithics** [keepkey/keepkey-desktop#214]
This message pops up when trying to install fresh on Windows

![Image](https://user-images.githubusercontent.com/47842709/199055078-38e06d63-ee86-48b1-9c15-bbc36dac85f5.png)

**Comment by amitojsingh366** [comment]
@illithics can you check if this is still happening, should be fixed `0.1.77` onwards

**Comment by battlejoose** [comment]
Can confirm this is fixed on windows install
