### ISSUE TITLE
(KICKBACK)(API)(DEVELOPER) feature, add status back to /status

### ISSUE THREAD

**Issue by BitHighlander** [keepkey/keepkey-desktop#238]
Some way to till if bridge is indeed online AND that device is unlocked and ready

Note: everything about 1-6 state is now gone

Need live/not live?

**Comment by BitHighlander** [comment]
no worky

![Image](https://user-images.githubusercontent.com/4935895/200200049-82b83742-7c75-4d6e-b65b-762e1e3daec1.png)

RC

go to api docs

click try it out

click send

see brokey

**Comment by elmutt** [comment]
THis should now return a string status like "connected" or "needsBootloader" etc
