### ISSUE TITLE
(FEATURE) Wallet connect on xdai

### ISSUE THREAD

**Issue by BitHighlander** [keepkey/keepkey-desktop#260]
https://omni.gnosischain.com/bridge

use wallet connect

try to connect on gnosis

**Comment by BitHighlander** [comment]
I think we can just store the "chain" in state and then respond to it on pairing.

Keepkey sdk should sign any chain ID given

Address stays the same regardless of chain


(Add a big batch of chains if possible)

(Understand this is only wallet connect and wont show in rest of app)

**Comment by elmutt** [comment]
on all eth chains
