### ISSUE TITLE
(WALLET_CONNECT)(BUG) inconsistent, Dapps shows connected, but desktop not recognizing it as connected.

### ISSUE THREAD

**Issue by BitHighlander** [keepkey/keepkey-desktop#291]

**Comment by BitHighlander** [comment]
![Image](https://user-images.githubusercontent.com/4935895/200194475-094cbb17-4728-491f-a2cf-b9304d1ba51a.png)

Steps to recreate


Pair app

Exit desktop app

(update/upgrade?)

Re-open app

go to dapp

hit wallet connect

see it connected

See it not connected in desktop

**Comment by elmutt** [comment]
same as https://github.com/keepkey/keepkey-desktop/issues/261
