### ISSUE TITLE
(WALLET_CONNECT) Tokenlaunch figured out how to crash the app.

### ISSUE THREAD

**Issue by BitHighlander** [keepkey/keepkey-desktop#549]

**Comment by BitHighlander** [comment]
recreate

go to dapp
https://tokenlauncher.com/

type in token info

**Comment by BitHighlander** [comment]
see crash on submit

**Comment by BitHighlander** [comment]
TODO handle an empty TO address for contract creation

**Comment by mrnerdhair** [comment]
As best I can tell, this occurs on the tokenlauncher side as it's serializing the walletconnect request but before it sends it over the pipe. I've added some pretty deep logging hooks which should catch any event coming in from the client app very early in the process, certainly before we have a chance to hand it to `hdwallet-keepkey-rest` or `keepkey-sdk` or anything else that might be capable of producing the error on our side, but nothing's triggering at all (other than the normal pair procedure) before the failure. It looks to me like an issue with tokenlauncher and walletconnect in general?

**Comment by mrnerdhair** [comment]
confirmed -- same error triggers when using walletconnect to the trust wallet ios app

**Comment by mrnerdhair** [comment]
(for reference, this doesn't crash our app -- the toast style they use looks a lot like ours though)
