### ISSUE TITLE
KeepKey Desktop for MAC Wont Install - 3.0.8.dmg not opening

### ISSUE THREAD

**Issue by JMacky2025** [keepkey/keepkey-desktop#673]
Im trying to download KeepKey from the main website but there is a 404 error.
https://github.com/keepkey/keepkey-desktop/releases/download/v3.0.8/KeepKey-Desktop-3.0.8.dmg

And when I try to download 3.0.8.dmg from the main github page, i cant install it as the application wont open. 
Im on a MacOs 11.7.10. Can you please help me install?

<img width="544" alt="Screen Shot 2024-04-25 at 9 20 22 PM" src="https://github.com/keepkey/keepkey-desktop/assets/168133120/46777b78-391c-4b63-9d62-c098953b1ad0">
<img width="1042" alt="Screen Shot 2024-04-25 at 9 19 39 PM" src="https://github.com/keepkey/keepkey-desktop/assets/168133120/960f8e7e-c71b-4506-91c3-536a3bff0c14">

**Comment by BitHighlander** [comment]
[KeepKey-Desktop-3.0.10-arm64.dmg](https://github.com/keepkey/keepkey-desktop/releases/download/v3.0.10/KeepKey-Desktop-3.0.10-arm64.dmg) URL now has prefix for build arch. Our mac signing as been migrated to apples new notary service. all links sitewide should by updated and correct now. thanks for reporting
