### ISSUE TITLE
debug: windows build

### ISSUE THREAD

**Issue by BitHighlander** [keepkey/keepkey-desktop#8]
A.C: patching client for windows builds

notes: requires https://github.com/shapeshift/lib/pull/347 merged into main. and a version bump on the npm package

**Comment by BitHighlander** [comment]
to bump packages on https://github.com/shapeshift/lib/tree/main/packages/caip create an empty commit with a correct title. 

https://github.com/shapeshift/lib/blob/main/CONTRIBUTING.md

**Comment by amitojsingh366** [comment]
@BitHighlander the windows builds now work fine after I fixed a few issues in #14
